/**
 * Offline ticket verification (spec 019 §P3, T311).
 *
 * WebCrypto mirror of `backend/app/services/ticket_signing.py::verify_ticket`
 * — used by the scanner PWA when `checkinApi.scan` fails with a network
 * error, so a valid QR can still be accepted at the gate without a round
 * trip. Must replicate the backend's exact MAC rule byte-for-byte or every
 * ticket will fail to verify client-side.
 *
 * Format: `FUNKE1.<payload_b64>.<mac_b64>`, both URL-safe unpadded base64.
 *
 * **Critical**: the MAC is computed over the ASCII bytes of the b64url
 * `payload_b64` SEGMENT ITSELF — NOT over the raw JSON bytes. This mirrors
 * `hmac.new(secret.encode(), payload_b64.encode("ascii"), hashlib.sha256)`
 * on the backend.
 *
 * Node-side parity fixture (guards against MAC-input drift — generated by
 * `ticket_signing.sign_ticket` with the exact call below; re-run it after
 * touching this file to confirm the two implementations still agree):
 *
 *   secret = "test-parity-secret-do-not-use-in-prod"
 *   sign_ticket(secret, "11111111-1111-1111-1111-111111111111", 1,
 *               "Jörg Müller", ["sa-abend", "so-vormittag"], True)
 *   code = "FUNKE1.eyJyIjoiMTExMTExMTEtMTExMS0xMTExLTExMTEtMTExMTExMTExMTExIiwicCI6MSwibiI6IkrDtnJnIE3DvGxsZXIiLCJzIjpbInNhLWFiZW5kIiwic28tdm9ybWl0dGFnIl0sIm8iOnRydWV9.D9kjJndYSx9anY19q1dXcQ"
 *   → verifyTicketLocal(secret, code) resolves to
 *     { r: "11111111-1111-1111-1111-111111111111", p: 1, n: "Jörg Müller",
 *       s: ["sa-abend", "so-vormittag"], o: true }
 *   Confirmed against Node's built-in `crypto.subtle` (no browser needed)
 *   during T311 implementation — no frontend test runner exists in this
 *   repo, so this fixture is the parity record, not an automated test.
 */

const TICKET_PREFIX = 'FUNKE1'

/** URL-safe unpadded base64 -> Uint8Array. */
function b64urlDecode(b64url) {
  const padded = b64url + '='.repeat((4 - (b64url.length % 4)) % 4)
  const base64 = padded.replace(/-/g, '+').replace(/_/g, '/')
  const binary = atob(base64)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}

async function importHmacKey(secret) {
  return crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  )
}

function constantTimeEqual(a, b) {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i]
  return diff === 0
}

/**
 * Verify a ticket code locally (no network) and return its payload, or
 * `null` on any failure (malformed code, wrong prefix, bad base64, bad
 * signature) — same contract as the backend's `verify_ticket`.
 * @param {string} secret - The event's `ticket_secret` (from the boot cache).
 * @param {string} code - The scanned ticket code.
 * @returns {Promise<object|null>} The decoded payload, or null.
 */
export async function verifyTicketLocal(secret, code) {
  try {
    const parts = code.split('.')
    if (parts.length !== 3) return null

    const [prefix, payloadB64, macB64] = parts
    if (prefix !== TICKET_PREFIX) return null

    // Sign the ASCII bytes of the b64url payload SEGMENT — not the decoded
    // JSON. This is the one rule that must never drift from ticket_signing.py.
    const key = await importHmacKey(secret)
    const signature = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(payloadB64))
    const expectedMac = new Uint8Array(signature).slice(0, 16)
    const actualMac = b64urlDecode(macB64)

    if (!constantTimeEqual(expectedMac, actualMac)) return null

    const payloadJson = new TextDecoder().decode(b64urlDecode(payloadB64))
    const payload = JSON.parse(payloadJson)
    if (typeof payload !== 'object' || payload === null) return null

    return payload
  } catch {
    return null
  }
}
